version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: interview_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: interviewdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
